---
include:
  - project: "azure-tools/ci-templates/tools"
    ref: "2.2.6"
    file:
      - "Linter.gitlab-ci.yml"

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_REF_NAME == "release"

.feature-branch:
  rules:
    - if: $CI_COMMIT_REF_NAME == "release"
      when: never
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: on_success
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: never
    - when: on_success

stages:
  - test

variables:
  IMAGE_GO: "gitlab-container-registry.skead.no/azure-tools/container-registry/go:0.3.1@sha256:17e8cab21b3adc479ecc2fdd3cc03ab7db7b686e7a01b7a61e6d76b3130e0a5b"

# Feature branch stages

megalinter-terraform-projects:
  extends: .megalinter-go
  allow_failure: true

go package code examination:
  image: ${IMAGE_GO}
  stage: .pre
  script:
    - go vet ./...
  rules:
    - !reference [.feature-branch, rules]
  tags:
    - intern

go security scanning:
  image: ${IMAGE_GO}
  stage: .pre
  script:
    - go install github.com/securego/gosec/v2/cmd/gosec@latest
    - gosec ./...
  rules:
    - !reference [.feature-branch, rules]
  tags:
    - intern

unit tests:
  image: ${IMAGE_GO}
  stage: test
  script:
    - echo "Prepare Go unit tests for provider"
  environment:
    name: dev
    action: verify
    deployment_tier: development
  rules:
    - !reference [.feature-branch, rules]
  tags:
    - intern

# Main branch stages

acceptance tests:
  image: ${IMAGE_GO}
  stage: test
  variables:
    RUNNER_SCRIPT_TIMEOUT: 20min
  script:
    - echo "Prepare Go acceptance tests for provider"
    - TF_ACC=1 go test -cover -timeout=20m -v ./...
  environment:
    name: test
    action: verify
    deployment_tier: testing
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - when: never
  tags:
    - intern

# Release branch

github release:
  image: ${IMAGE_GO}
  stage: test
  script:
    - echo "Sync with GitHub"
  environment:
    name: prod
    action: verify
    deployment_tier: production
  rules:
    - if: $CI_COMMIT_REF_NAME == "release"
      when: on_success
    - when: never
  tags:
    - intern
