ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

[rule.package-comments]
    Disabled = true
[rule.unused-parameter]
    Arguments = [ { allowRegex = "^(ctx|req)$" } ]
